### ISSUE TITLE
What is error 30 on some title ?

### ISSUE THREAD

**Issue by DavidBabel** [Destiny1984/XCI-Cutter#10]
On some titles like : 
- Night of azure 2
- Snipperclips

return a ERR30 on batch processing.

**Comment by Destiny1984** [comment]
Error 30 means: 
found data after the end of the gamepartiton.

It is known that this error occurs on snipperclips, since bbb released a bad dump of that game (they re-released it with a proper dump)

But it's the first time that someone reports this error for a different game.

**Comment by DavidBabel** [comment]
For the reccord, got a BBB extract for Wild Gun Reloaded that has the same issue

**Comment by Destiny1984** [comment]
That's strange. Maybe bbb released bad dumps (again), or Nintendo altered somehow the partition layout.

I've added a "fast mode". You could use that mode to force trimming of these Error 30 files,
since it disables the safety check.
When backuploaders are available, we should test especially these games, to see if the data
after gamepartition is somehow important or just garbage (which can be trimmed without any issue)

By using fast mode, make sure that you create a backup of these games beforehand.
